### ISSUE TITLE
‘PSM2_MQ_FLAG_GDRCPY_ONLY’ undeclared

### ISSUE THREAD

**Issue by flyingdown** [cornelisnetworks/psm2-nccl#2]
when I run make, I get this error:

> src/psm2_nccl_net.c: In function ‘psm2_nccl_isend’:
src/psm2_nccl_net.c:671:53: error: ‘PSM2_MQ_FLAG_GDRCPY_ONLY’ undeclared (first use in this function); did you mean ‘PSM2_MQ_FLAG_SENDSYNC’?
  int rc = psm2_mq_isend(comm->mq, comm->rem_epaddr, PSM2_MQ_FLAG_GDRCPY_ONLY, comm->tag, data, size, (void*)r, &r->req);
                                                     ^~~~~~~~~~~~~~~~~~~~~~~~
                                                     PSM2_MQ_FLAG_SENDSYNC
src/psm2_nccl_net.c:671:53: note: each undeclared identifier is reported only once for each function it appears in
src/psm2_nccl_net.c: In function ‘psm2_nccl_irecv’:
src/psm2_nccl_net.c:696:62: error: ‘PSM2_MQ_FLAG_GDRCPY_ONLY’ undeclared (first use in this function); did you mean ‘PSM2_MQ_FLAG_SENDSYNC’?
  int rc = psm2_mq_irecv(comm->mq, comm->tag, ~((uint64_t)0), PSM2_MQ_FLAG_GDRCPY_ONLY, data, size, (void*)r, &r->req);
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~
                                                              PSM2_MQ_FLAG_SENDSYNC

can not find `PSM2_MQ_FLAG_GDRCPY_ONLY` in any header file, project [https://github.com/cornelisnetworks/opa-psm2/tree/PSM2_11.2.NCCL](url)

**Comment by BrendanCunningham** [comment]
For whatever reason, the GitHub search of opa-psm2 for `PSM2_MQ_FLAG_GDRCPY_ONLY` does not return any results. But it is there - [psm2_mq.h, line 524](https://github.com/cornelisnetworks/opa-psm2/blob/2640c7104f0f943fcadeb7fea9e8c117394b64c7/psm2_mq.h#L524).

Did you build and install opa-psm2/PSM2_11.2.NCCL to system-wide locations (i.e. PSM2 header files to /usr/include)? If so, do you see GDRCPY in /usr/include/psm2_mq.h? If not, did you specify `PSM2_INCLUDE` and `PSM2_LIB` when making the PSM2-NCCL plugin? Could you please provide the `make` command you're using to build PSM2-NCCL? Thanks.

**Comment by flyingdown** [comment]
Thanks for your reply. I just used the default opa-psm2 in the system which somebody had installed already. It reports error below when I build the opa-psm2/PSM2_11.2.NCCL, but I use the ROCM platform.

> error: #error Please update CUDA driver, required minimum version is 7.0

I should slove this problem first. By the way, would  opa-psm2/PSM2_11.2.NCCL will consider ROCM platform in the future?

**Comment by flyingdown** [comment]
Thanks for your reply. I made a mistake. Just used the default opa-psm2 in the system which someone installed already.
